spring:
  application:
    name: auth-app-backend
  profiles:
    active:
      - dev

server:
  port: 8082


#configuration
#datbase configuration
#mysql configuration

#email configuration
#oauth2 configuration